// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_First.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Code_First.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("Code_First.Example2", b =>
                {
                    b.Property<int>("Nr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Nr");

                    b.ToTable("Examples2");
                });

            modelBuilder.Entity("Code_First.Example3", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Examples3");
                });

            modelBuilder.Entity("Code_First.Example4", b =>
                {
                    b.Property<int>("Nr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Nr")
                        .HasName("Primary");

                    b.ToTable("Examples4");
                });

            modelBuilder.Entity("Code_First.Example5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value2")
                        .HasColumnType("longtext");

                    b.Property<string>("Value4")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Value5")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value6")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Value11");

                    b.Property<string>("Value7")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value8")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value9")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Value10");

                    b.HasKey("Id");

                    b.ToTable("Examples5");
                });
#pragma warning restore 612, 618
        }
    }
}
